services:
  - type: web
    name: portal-escalas-gnr
    runtime: python
    buildCommand: pip install -r requirements_portal.txt
    startCommand: uvicorn portal.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
