gsheet_url = "https://docs.google.com/spreadsheets/d/1y40O14e-pZRFn92Dyn3JkE5gshWZl7XOwVvlP1uBazg/edit"

[gcp_service_account]
type = "service_account"
project_id = "escala-489421"
private_key_id = "1638fb27186ed693dc8f850da3ebd11800a14b05"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxpwf9f2C3RwGo
qRzRj5lQ9xOvYpwMMMMx/azFvMcBdC0vCApw/2ZkK8w/QUg34J0WvbMxF1SXQuvA
3zXris89v8szUpv/6vFhLovuaW3BVesQPHNY8c9wkBY4hYx4TX3oCn3boC6cZlBz
+kPu4bB3qv7jxcNn2BijQOLqrkz/OhhQZih8unFWrV4/a0LcjsyeglyLTGLPTLFH
aGAeRSe2rvFF+PH6K6mZ4lNoz9p5HD7SNqInkQlci8fxHsDNPbc2vmERoDBcwhQ0
uehZrgM+M27PcxvoEcc3qirZdYx/7LGLjLxsCkgL1fvaXFWnlC13achQcEehQCkv
ySuvIObHAgMBAAECggEADDZzXNXuNtXxeJVySbsZdcYb2v69w4jGonUnSiCu0vFt
pGy6aweOaRcptLTZhh3cLr1ecuLWXzUBMq0lmR+zHNzxLIINVLaOCXmYXQzFDXlz
7hXPHYTiFyw7RX9zfKxhxMXpM7lQpafS+BDIWBpjy0DnbOPM3yKtREEoWFcggUXG
aKoVnTLMAx5nFsorbbnpJOohIIdpa25xOic8g8imNx95j0dHqFBkRVJiUR3320IE
xilS126li5FMajBcDu+P2mS8m5wyrNLFeyem8cSqHA0FmApSfPCOsteWj9SpB5et
6HWggcnk/la1p34Sq9sdrEdd/7pJ6Sf0fUEiQDprgQKBgQDlE0qBrRletRbK9BXu
2Lqp8K2FHf3vNToH5/xThG+Mn+60KzWqYlRtxX8aP+hAE6NN83q2rFs6/MTK5YQU
xmCAQg+tL6GT7IMyusVO8Cc7R0UECvzhewb94VIuJ3JjMIlEshCABkCHrgJdflOU
vhy8bbfS1hb9ydK2ulMk2yWdUQKBgQDGiHaWkB4C6lWFlt9Q/YpBgVMYu/4b2/5l
TfhvrXdlT41dEjrRH9SzSOkKI8/8XOFqOwtpu9OQH5jGTGmaHHpWlseb/375Q8RR
fqoBgRxXpQGRMbcqBwt9J56+reO/OpbbrnqXCtAb37Md+B6aAx/GE8nFMXMHu5e0
YP0jduhclwKBgQCTIjbi37nB2PKQ3QIRbWdHq+zn6YGm2TsyxNCPHCtB2Z/KXU6U
559u+kFPLOkR7wsfEForZr0aQCxuXcjeRyTIfKXxCPzxNCJ4vPnqX9ny+y3bEOuo
MAsnmkfcmT2hdBVW6EAs2tcrzpp6Tp+ElC+E37wIUbZmv/D1qOuqao/YYQKBgFlU
9A9hf6+OI7c9oPR/cSNyfqKFjJyai8inod8Wbb/vYMt9NWv956ZYa0u9u4txe5hi
QwtrkZGrNgIcRfQrVjz6EY03FLoybPbCiNqubsNdIuxjM2i8zMWe+0YPVogoY9Mr
mku2eNfh+2XDzHk+aKCnLMYHLxxOo79tWNoJWhq3AoGBAI6yO75Y6wlcLN9hMUur
ALpy0eG7tpdSNKwuVDOvsu7ulg5J5YZBkSHjLJtL8p5Uylko6F5mesy5EHtBKRHg
kMY4Z4uJqrKDliEXeggBPRK/6PGtQqFwSPHgRVb1PVIWLKHX4Lkx1T43/jCGm4WM
11FZBme1DbvT2a2lu7Thkrsl
-----END PRIVATE KEY-----
"""
client_email = "gnr-escala-bot@escala-489421.iam.gserviceaccount.com"
client_id = "105499088549392880284"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gnr-escala-bot%40escala-489421.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
